export const CHAIN_LOCAL_WALLET = 'CHAIN_LOCAL_WALLET';
export const CHAIN_LOCAL_CONNECTION = 'CHAIN_LOCAL_CONNECTION';
export const CHAIN_GAME = 'CHAIN_GAME';
export const CHAIN_NEXT_TURN = 'CHAIN_NEXT_TURN';
